version: '3.8'

services:
  # mongo_seed:
  #   image: mongo:3.8
  #   command: mongorestore --drop --db test /tmp/dump
  #   volumes:
  #     - /tmp/dump:/tmp/dump
  #   depends_on:
  #     - mongo
  api:
    depends_on:
      - mongo
    image: nesty
    # build: .
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      .env
      # - .env
    ports:
      - $PORT:3000
    restart: always
  # mysql:
  # web:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASS
      - MONGO_INITDB_DATABASE=$MONGO_DB
    volumes:
      - mongo_data:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  mysqldb:
    image: mysql
    ports:
      - 33061:3306
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASS
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=my_node_app
      - MYSQL_PASSWORD=$MYSQL_PASS
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
volumes:
  mongo_data:
  mysql_data:
